# wrangler.toml

name = "url-shortener"
main = "src/index.js"
compatibility_date = "2023-10-30"

# This binding allows the worker to access the KV namespace.
# The `id` will be automatically created and filled in during the deploy process.
[[kv_namespaces]]
binding = "URL_STORE"
id = "dba5cb52c7474f08bdc3d0d3b9a3627a"
preview_id = ""

# This section defines secret variables.
# The user will be prompted to enter these values during deployment.
[vars]
TELEGRAM_BOT_TOKEN = "7560515184:AAFWyDMONo78U4dulHpf4WuQtPheRVwUc_M"
GITHUB_REPO_URL = " https://github.com/Johndevils/url-shortner- "
